# Generated by Django 3.2.12 on 2022-03-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
