# Generated by Django 3.2.12 on 2022-03-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel',
        ),
    ]
