# Generated by Django 3.2.12 on 2022-03-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20220319_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='slug',
        ),
    ]
