# Generated by Django 3.2.12 on 2022-03-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_auto_20220320_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='category',
            new_name='categories',
        ),
    ]
