# Generated by Django 3.2.12 on 2022-03-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_auto_20220320_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='category',
            new_name='categories',
        ),
    ]
