# Generated by Django 3.2.12 on 2022-03-20 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0017_rename_category_blogmodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='popular',
            field=models.ManyToManyField(blank=True, related_name='popular', to=settings.AUTH_USER_MODEL),
        ),
    ]
