# Generated by Django 3.2.12 on 2022-03-24 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0018_blogmodel_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='popular',
            field=models.ManyToManyField(editable=False, related_name='popular', to=settings.AUTH_USER_MODEL),
        ),
    ]
