# Generated by Django 3.2.12 on 2022-03-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_alter_blogmodel_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
